### PR TITLE
Create iqlusion.json

### PR DESCRIPTION
**Pull request by zmanian**
Iqlusion gen tx for noble

### CODE REVIEW

**Review by danbryan — CHANGES_REQUESTED** [review]
@zmanian do you mind adding a memo with a p2p ID. I know it's not required, but it can prevent the gentx collection from working if we have mixed values as we learned in testnet.

**Comment by zmanian** [comment]
We are working on it

**Comment by zmanian** [comment]
Resolved

**Review by danbryan — APPROVED** [review]
Looks good to me

**Review by boojamya — APPROVED** [review]

**Pull request merged**
